version: '2'
services:
  postgres:
    build: ./docker/postgresql
    ports:
      - "5433:5432"
    volumes:
      - "./volumes/postgres:/bitnami/postgresql"
    environment:
      POSTGRESQL_USERNAME: test
      POSTGRESQL_PASSWORD: test
      POSTGRESQL_DATABASE: test

  php-fpm:
    build: ./docker/php
    links:
      - postgres
    volumes:
      - "./app:/app"
    environment:
      DB_HOST: postgres

  nginx:
    image: nginx:1.19.1
    volumes:
      - "./app:/app"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php-fpm
    ports:
      - "8080:80"

